# Generated by Django 2.0.6 on 2018-08-14 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=256)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 8, 14, 7, 38, 28, 422760))),
                ('media', models.CharField(max_length=256)),
                ('article', models.TextField()),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
