# Generated by Django 2.0.6 on 2018-08-14 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 7, 41, 44, 861941)),
        ),
    ]
