# Generated by Django 2.0.7 on 2018-08-23 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180814_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 6, 45, 3, 835080)),
        ),
    ]
