# Generated by Django 2.0.6 on 2018-09-22 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180922_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 16, 29, 12, 814834)),
        ),
    ]
